### PR TITLE
Added method to send list message

### PR DESCRIPTION
**Pull request by ibnusyawall**
[update]

I added method for sending list message xD

use:
```js
conn.sendListMessage(jid, { buttonText: 'Example', description: 'Send list message', title: 'Title of message list' }, [
   { title: 'Example title list 01', description: 'Example description', rowId: '01' }
])
```

note: last of parameter is required and this is section rows of list message

screenshot:

Screenshot_20210705-233245
Screenshot_20210705-233251

thanks.

### CODE REVIEW

**Comment by rawars** [comment]
Hello, you don't know how I can send buttons?

**Comment by ibnusyawall** [comment]
> Hello, thanks for your contribution, don't you know how I can send buttons?

I don't understand what you mean

**Comment by rawars** [comment]
Hello, if you know how to send buttons as they are sent in the official api, because I see in your code that there is a button.
Screenshot_2021-07-06-00-27-35

**Comment by ibnusyawall** [comment]
> Hello, if you know how to send buttons as they are sent in the official api, because I see in your code that there is a button.
> Screenshot_2021-07-06-00-27-35

my code is to send a list message but not send a button message like the official whatsapp api, this topic has been discussed before on discord Baileys, you can check more about that discussion on [Baileys Discord Server](https://discord.gg/w6JF9NmH)

**Comment by adiwajshing** [comment]
This is pretty cool @ibnusyawall, thanks for the contribution.

**Comment by vasani-arpit** [comment]
@adiwajshing @ibnusyawall Has anyone tested this in a WA Business app? I am getting error while sending a message. **This works completely fine in normal WA.**

image

**Comment by ibnusyawall** [comment]
> @adiwajshing @ibnusyawall Has anyone tested this in a WA Business app? I am getting error while sending a message. **This works completely fine in normal WA.**
> 
> image

right, just works fine on normal whatsapp but can't send on business whatsapp, and i don't know why it's so 3>

**Comment by Caossns** [comment]
> [update]
> 
> I added method for sending list message xD
> 
> use:
> 
> ```js
> conn.sendListMessage(jid, { buttonText: 'Example', description: 'Send list message', title: 'Title of message list' }, [
>    { title: 'Example title list 01', description: 'Example description', rowId: '01' }
> ])
> ```
> 
> note: last of parameter is required and this is section rows of list message
> 
> screenshot:
> 
> Screenshot_20210705-233245
> Screenshot_20210705-233251
> 
> thanks.

teach me

**Comment by Caossns** [comment]
> [update]
> 
> I added method for sending list message xD
> 
> use:
> 
> ```js
> conn.sendListMessage(jid, { buttonText: 'Example', description: 'Send list message', title: 'Title of message list' }, [
>    { title: 'Example title list 01', description: 'Example description', rowId: '01' }
> ])
> ```
> 
> note: last of parameter is required and this is section rows of list message
> 
> screenshot:
> 
> Screenshot_20210705-233245
> Screenshot_20210705-233251
> 
> thanks.

Ko d gw g work

**Comment by Caossns** [comment]
> [update]
> 
> I added method for sending list message xD
> 
> use:
> 
> ```js
> conn.sendListMessage(jid, { buttonText: 'Example', description: 'Send list message', title: 'Title of message list' }, [
>    { title: 'Example title list 01', description: 'Example description', rowId: '01' }
> ])
> ```
> 
> note: last of parameter is required and this is section rows of list message
> 
> screenshot:
> 
> Screenshot_20210705-233245
> Screenshot_20210705-233251
> 
> thanks.

@ibnusyawall Ko gw gbsa ya

**Comment by RynKings** [comment]
> Hello, if you know how to send buttons as they are sent in the official api, because I see in your code that there is a button.
> Screenshot_2021-07-06-00-27-35

#590 use this protobuf supported for sending buttons

```async function sendButton(id){
    buttonMessage = WAMessageProto.ButtonsMessage.fromObject({
        contentText: 'Maafin aku ya sayangg 🥺🥺🥺',
        footerText: 'It\'s me Ryns',
        buttons: [{
            buttonId: 'id1',
            buttonText: {
                displayText: 'Iyya'
            },
            type: 1
        },{
            buttonId: 'id2',
            buttonText: {
                displayText: 'Nggk'
            },
            type: 1,
            nativeFlowInfo: {
                name: 'Test',
                paramsJson: 'anu'
            }
        }],
        headerType: 1,

    })
    message = WAMessageProto.Message.fromObject({
        buttonsMessage: buttonMessage
    })
    let waButtonMessage = await wa.prepareMessageFromContent(id, message, {})
    await wa.relayWAMessage (waButtonMessage, { waitForAck: true })
    return waButtonMessage
}```

![image](https://user-images.githubusercontent.com/39035843/125359610-1bc1fa00-e39d-11eb-85a7-71cafd755eaf.png)

**Comment by rawars** [comment]
> > Hello, if you know how to send buttons as they are sent in the official api, because I see in your code that there is a button.
> > Screenshot_2021-07-06-00-27-35
> 
> image
> 
> #590 use this protobuf supported for sending buttons
> 
> ```
> async function sendButton(id){
>     buttonMessage = WAMessageProto.ButtonsMessage.fromObject({
>         contentText: 'Maafin aku ya sayangg 🥺🥺🥺',
>         footerText: 'It\'s me Ryns',
>         buttons: [{
>             buttonId: 'id1',
>             buttonText: {
>                 displayText: 'Iyya'
>             },
>             type: 1
>         },{
>             buttonId: 'id2',
>             buttonText: {
>                 displayText: 'Nggk'
>             },
>             type: 1,
>             nativeFlowInfo: {
>                 name: 'Test',
>                 paramsJson: 'anu'
>             }
>         }],
>         headerType: 1,
> 
>     })
>     message = WAMessageProto.Message.fromObject({
>         buttonsMessage: buttonMessage
>     })
>     let waButtonMessage = await wa.prepareMessageFromContent(id, message, {})
>     await wa.relayWAMessage (waButtonMessage, { waitForAck: true })
>     return waButtonMessage
> }
> ```

Hello friend, follow the link but I see that it is closed, how can I apply it? I'm interested in implementing interactive buttons.

**Pull request merged**
