### PR TITLE
Add support for group invite

### PR DESCRIPTION
**Pull request by FaizBastomi**
based on this issue at #495 

how to send:
```js
conn.sendMessage(jid, { groupName: string, groupJid: string, inviteCode: string, inviteExpiration: number, caption: string, jpegThumbnail: Uint8Array }, MessageType.groupInviteMessage)
```

> inviteCode and inviteExpiration from
IMG_20210525_225943

test result:
IMG-20210525-WA0905

### CODE REVIEW

**Comment by AlenSaito1** [comment]
This would be really useful

**Comment by ferhacks** [comment]
omg thx forma this!

**Comment by PurpShell** [comment]
niceeeee

**Comment by sostenesapollo** [comment]
weasome

**Comment by FaizBastomi** [comment]
up

**Comment by ChalanaN** [comment]
Does this available in newer versions? 😕

**Pull request merged**
