### PR TITLE
fix typo example send list message in readme

### PR DESCRIPTION
**Pull request by ZefianAlfian**

### CODE REVIEW

**Comment by RynKings** [comment]
image

sorry I think it's description not descriptions

**Comment by ZefianAlfian** [comment]
the correct one is descriptions sir, I have tried it and there is no problem

**Comment by RynKings** [comment]
image
the description is not filled when I use descriptions

image

**Comment by ibnusyawall** [comment]
> image
> 
> sorry I think it's description not descriptions

Screenshot (87) [#584](https://github.com/adiwajshing/Baileys/pull/584/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)

he corrected the example you updated earlier, and it really is a typo in the rows section which should be descriptions and not description.

**Comment by ZefianAlfian** [comment]
Sorry for my mistake ._.

**Pull request closed without merging**
