### PR TITLE
isomorphic websocket

### PR DESCRIPTION
**Pull request by itacirgabral**
https://github.com/adiwajshing/Baileys/issues/244

I tested it against some of my runtimes in backend/node and works fine.
@zoutepopcorn could you test it in your frontend/extension setup?

### CODE REVIEW

**Comment by adiwajshing** [comment]
I'm not sure if this would work well on a browser runtime because Baileys has dependencies on other node js libraries like `fs` -- more work might be required to make it completely isomorphic.

**Comment by itacirgabral** [comment]
> more work might be required to make it completely isomorphic.

Browser support may open a lot more use cases. Is it in the Baileys's goals? What do you think about it?

websocket cors:
https://stackoverflow.com/questions/23674199/why-is-there-no-same-origin-policy-for-websockets-why-can-i-connect-to-ws-loc#answer-37837709

Is there node dependencies in the baileys's core?
`Buffer` and `fs` have browserify wrappers.

`qrcode-terminal` and `pino` may have no room on frontend.

**Comment by adiwajshing** [comment]
> Browser support may open a lot more use cases. Is it in the Baileys's goals? What do you think about it?

100% a great thing to have. However, let's have a running version on the browser before merging this PR?

**Comment by itacirgabral** [comment]
I'm using verdaccio to publish the pull requesto to my local registry as `isobaileys`
```
yarn add -g verdaccio
verdaccio &
yarn config set registry http://localhost:4873
```

I've load baileys for create react app:

```typescript
import { useEffect } from 'react';
import { WAConnection } from 'isobaileys';

function App() {
  useEffect(() => {
    const conn = new WAConnection()

    conn.connect().then(() => {
      console.log('connected')
    })
  });

  return (<></>)
}
```

```
{error: TypeError: _a.removeAllListeners is not a function
3.Connect.js:87 WebSocket connection to 'wss://web.whatsapp.com/ws' failed: Error during WebSocket handshake: Unexpected response code: 403
```

[`isomorphic-fetch`](https://github.com/matthew-andrews/isomorphic-fetch) is another easy wrapper

**Pull request closed without merging**
