### PR TITLE
Prank group with bug ephemeral

### PR DESCRIPTION
**Pull request by frmdeveloper**

### CODE REVIEW

**Comment by FebbAdityaN** [comment]
why make function bugs? The bug has been fixed stupidly, and you're committing it again

**Comment by frmdeveloper** [comment]
but this is a different function. toggle message while still working

**Comment by dhyZx** [comment]
LOLLLLLLLLL

**Comment by FaizBastomi** [comment]
why? are you stupid? this was fixed in the previous update and why are you reverting back?
close this PR we don't need this in Baileys, This only proves that you are stupid.

**Comment by rayyreall** [comment]
Stress

**Comment by frmdeveloper** [comment]
Saya sehat

**Comment by bukan-jojo** [comment]
Bocil kontol ya gini

**Comment by Gimenz** [comment]
arghh. stupid dickhead

**Comment by Yuuka77** [comment]
Stres

**Comment by Nafiz0110** [comment]
goblog

**Comment by frmdeveloper** [comment]
Sudah lah

**Pull request closed without merging**
