### PR TITLE
feat: send text message defalt type conversation

### PR DESCRIPTION
**Pull request by huangzhong0406**

### CODE REVIEW

**Comment by adiwajshing** [comment]
Not sure why this PR is required

**Comment by huangzhong0406** [comment]
> Not sure why this PR is required

When I need to send a message of type conversation ，I can't set it, it's always extendedTextMessage，so I made a modification

**Comment by adiwajshing** [comment]
I think you should just modify your code instead of updating the default type like this

**Comment by huangzhong0406** [comment]
ok , thanks

**Pull request closed without merging**
