### PR TITLE
send more than 1 contact

### PR DESCRIPTION
**Pull request by hardianto02**

### CODE REVIEW

**Comment by hardianto02** [comment]
Screenshot_2021-12-16-17-39-14-594_com whatsapp

**Comment by frmdeveloper** [comment]
indonesia

**Comment by hardianto02** [comment]
> indonesia



> indonesia

yeess sir

**Comment by frmdeveloper** [comment]
> yeess sir

Don't call me "sir"

**Comment by adiwajshing** [comment]
A more robust fix:

https://github.com/adiwajshing/Baileys/pull/696/commits/6c4a9c7354a6da393e9b4fbe9bc3104e14a5dfca

**Pull request closed without merging**
