### PR TITLE
add support for labels on chats and messages

### PR DESCRIPTION
**Pull request by injitools**
open for discussion about realization

### CODE REVIEW

**Comment by azudindaem** [comment]
suggest to change variable **labaled** 

Would you mind to put this implementation in chatModify so user can use sock.chatModify

**Comment by injitools** [comment]
> suggest to change variable **labaled**

"labaled" from proto description of protocol. i'm not change it. it's standart whatsapp parameter


> Would you mind to put this implementation in chatModify so user can use sock.chatModify

it's already in chatModify and i add two helper functions for creating mod for it.
```

const setChatLabel = async(jid: string, labelId: string, labaled: boolean = true) => {
	return chatModify({
		type: LabelAssociationType.JID,
		labelId,
		labelAssociationAction: { labaled },
	}, jid)
}
const setMessageLabel = async(jid: string, messageId: string, labelId: string, labaled: boolean = true) => {
	return chatModify({
		type: LabelAssociationType.MESSAGE,
		labelId,
		messageId,
		labelAssociationAction: { labaled },
	}, jid)
}
```
so you just call it from sock
```
sock.setChatLabel(msg.key.remoteJid!, labels[0].id)
sock.setMessageLabel(msg.key.remoteJid!, msg.key.id!, labels[1].id)
```

**Comment by azudindaem** [comment]
you may use "labelled" instead of "labaled"

it would be nice if you can make it like

``` ts
  await sock.chatModify({
    addLabel: {
      label: '1',
    },
  },
  '123456@s.whatsapp.net')
  
  await sock.chatModify({
    removeLabel: {
      label: '1',
    },
  },
  '123456@s.whatsapp.net')
  ```

**Comment by injitools** [comment]
> you may use "labelled" instead of "labaled"
> 
> it would be nice if you can make it like

make it work like you example

also add `addMessageLabel` and `removeMessageLabel`

**Pull request closed without merging**
