### PR TITLE
Add support for buttons message

### PR DESCRIPTION
**Pull request by RynKings**

### CODE REVIEW

**Review by RynKings — COMMENTED** [review]
#146

**Comment by RynKings** [comment]
sorry it's not clear to commit, I'm sleepy haven't slept :"

**Comment by adiwajshing** [comment]
@RynKings does this work?

**Comment by vasani-arpit** [comment]
@RynKings  Is this same as #583 ?

**Comment by RynKings** [comment]
> @RynKings does this work?



Yeah it work..

**Comment by ibnusyawall** [comment]
> _No description provided._

This is very nice! did you debug this commit first? I get an error like this:

img

**Comment by RynKings** [comment]
> > _No description provided._
> 
> This is very nice! did you debug this commit first? I get an error like this:
> 
> img

Sorry I am sleepy, I've been debug it but on another file

**Comment by ibnusyawall** [comment]
c4549ead-fc8c-44cf-bc11-0841e3599003
yeay, work, nice!

**Comment by adiwajshing** [comment]
@RynKings just ensure everything is working correctly, I'll merge then. Damn nice work.

**Comment by RynKings** [comment]
> @RynKings just ensure everything is working correctly, I'll merge then. Damn nice work.

I think everything is working properly...

**Comment by RynKings** [comment]
> @RynKings just ensure everything is working correctly, I'll merge then. Damn nice work.

I've tried it and it seems everything is working properly...

**Comment by ekoeryanto** [comment]
orang indonesia 🤣  hati-hati kesempatan kena blokir meningkat gara2 list message atau button message

**Comment by jonasfreitas-dev** [comment]
image

Perfeito!

**Comment by vasani-arpit** [comment]
@RynKings @adiwajshing 

Was adding the example mentioned in readme to the example.ts file. I ran into this error message. 
image

**[Solution]** I believe toJSON needs to ma made as static method. 
image

What do you think?

**Comment by RynKings** [comment]
> @RynKings @adiwajshing
> 
> Was adding the example mentioned in readme to the example.ts file. I ran into this error message.
> image
> 
> **[Solution]** I believe toJSON needs to ma made as static method.
> image
> 
> What do you think?

ah sorry have you test it as any ?

const buttonMessage: any = {}

**Comment by vasani-arpit** [comment]
> ah sorry have you test it as any ?

Yes. Any is working but then it looses the meaning of having TypeScript.

**Comment by creuza** [comment]
`const send = await conn.sendMessage(id, buttonMessage, MessageType.buttonsMessage)`

(node:3656)` UnhandledPromiseRejectionWarning: BaileysError: Unexpected status in 'action': Bad Request(400)

**i receive this**

**Comment by nugraizy** [comment]
> image
> 
> Perfeito!

how does yours has 4 buttons? i try added one more buttons but the buttons just appear 3

**Comment by barkerpedro** [comment]
Send buttons with images:

```typescript
let content: any = fs.readFileSync('./Media/cat.jpeg') // change for file type
const media = await conn.prepareMessage(id, content, MessageType.image) // change for file type

const buttons = [
  {buttonId: 'id1', buttonText: {displayText: 'Button 1'}, type: 1},
  {buttonId: 'id2', buttonText: {displayText: 'Button 2'}, type: 1}
]
const buttonMessage = {
    contentText: "Hi it's button message",
    footerText: 'Hello World',
    buttons: buttons,
    headerType: 4, // change for file type
    imageMessage: media.message.imageMessage // change for file type
}
const sendMsg = await conn.sendMessage(id, buttonMessage, MessageType.buttonsMessage)
```

Send buttons with document:
```typescript
    headerType: 3,
    documentMessage: media.message.documentMessage
```
Send buttons with video:
```typescript
    headerType: 5,
    videoMessage: media.message.videoMessage
```
Send buttons with location:
```typescript
    headerType: 6,
    locationMessage: media.message.locationMessage
 ```

**Comment by RynKings** [comment]
> > image
> > Perfeito!
> 
> how does yours has 4 buttons? i try added one more buttons but the buttons just appear 3

Idk, at whatsapp web & Ios it appears more than 3 button 
but on Android it just appears 3 button

**Comment by jonasfreitas-dev** [comment]
> > how does yours has 4 buttons? i try added one more buttons but the buttons just appear 3
> 
> Idk, at whatsapp web & IOS it appears more than 3 button
> but on Android it just appears 3 button

Really, I realized that too, on android they only have 3 buttons.

**Comment by tukangparkir** [comment]
Kenapa yah Tombolnya tidak bisa membalas otomatis, walaupun sudah di klik?
tombol tidak bisa dipakai untuk autoreplay.
padahal kalau diketik biasa bisa

**Comment by tukangparkir** [comment]
image

**Comment by tukangparkir** [comment]
@RynKings bisa minta tolong?

**Comment by RynKings** [comment]
> @RynKings bisa minta tolong?

please include it with the code...

**Comment by tukangparkir** [comment]
Im make code with here

`/ send button response
app.post('/v2/send-button', async (req, res) => {
    
    if (conn.state == 'open') {
        const message = req.body.message;
        const button1 = req.body.button1;
        const button2 = req.body.button2;

        const footer = req.body.footer;

        if (req.body.number.length > 15) {
            var number = req.body.number;
        } else {
            var number = phoneNumberFormatter(req.body.number);
            var numberExists = await conn.isOnWhatsApp(number);
            if (!numberExists) {
                return res.status(422).json({
                    status: false,
                    message: 'The number is not registered'
                });
            }
        }

    const buttons = [
      {selectedButtonId: 'id1', contextInfo: {selectedDisplayText: button1 }, type: 1},
      {selectedButtonId: 'id2', contextInfo: {selectedDisplayText: button2 }, type: 1},
    ]  
    
    const buttonpesan = {
        contentText: message,
        footerText: footer,        
        buttons: buttons,
        headerType: 1 }

        conn.sendMessage(number, buttonpesan, MessageType.buttonsMessageResponse).then(response => {
                
            res.status(200).json({
                status: true,
                response: response
            });
        }).catch(err => {
            res.status(500).json({
                status: false,
                response: err
            });
        });
    } else {
        res.status(500).json({
            status: false,
            response: 'Please scan the QR before use this API'
        });
    } 
    

});`

**Comment by tukangparkir** [comment]
@RynKings

**Comment by RynKings** [comment]
> Im make code with here
> 
> `/ send button response
> app.post('/sen/send-button', async (req, res) => {
>     
>     if (conn.state == 'open') {
>         const message = req.body.message;
>         const button1 = req.body.button1;
>         const button2 = req.body.button2;
> 
>         const footer = req.body.footer;
> 
>         if (req.body.number.length > 15) {
>             var number = req.body.number;
>         } else {
>             var number = phoneNumberFormatter(req.body.number);
>             var numberExists = await conn.isOnWhatsApp(number);
>             if (!numberExists) {
>                 return res.status(422).json({
>                     status: false,
>                     message: 'The number is not registered'
>                 });
>             }
>         }
> 
>     const buttons = [
>       {selectedButtonId: 'id1', contextInfo: {selectedDisplayText: button1 }, type: 1},
>       {selectedButtonId: 'id2', contextInfo: {selectedDisplayText: button2 }, type: 1},
>     ]  
>     
>     const buttonpesan = {
>         contentText: message,
>         footerText: footer,        
>         buttons: buttons,
>         headerType: 1 }
> 
>         conn.sendMessage(number, buttonpesan, MessageType.buttonsMessageResponse).then(response => {
>                 
>             res.status(200).json({
>                 status: true,
>                 response: response
>             });
>         }).catch(err => {
>             res.status(500).json({
>                 status: false,
>                 response: err
>             });
>         });
>     } else {
>         res.status(500).json({
>             status: false,
>             response: 'Please scan the QR before use this API'
>         });
>     } 
>     
> 
> });`

Are you sure you have to follow the example ?

**Comment by tukangparkir** [comment]
yes sure

**Comment by SL-Alpha-X** [comment]
> Send buttons with images:
> 
> ```ts
> let content: any = fs.readFileSync('./Media/cat.jpeg') // change for file type
> const media = await conn.prepareMessage(id, content, MessageType.image) // change for file type
> 
> const buttons = [
>   {buttonId: 'id1', buttonText: {displayText: 'Button 1'}, type: 1},
>   {buttonId: 'id2', buttonText: {displayText: 'Button 2'}, type: 1}
> ]
> const buttonMessage: any = {
>     contentText: "Hi it's button message",
>     footerText: 'Hello World',
>     buttons: buttons,
>     headerType: 4, // change for file type
>     imageMessage: media.message.imageMessage // change for file type
> }
> const sendMsg = await conn.sendMessage(id, buttonMessage, MessageType.buttonsMessage)
> ```
> 
> Send buttons with document:
> 
> ```ts
>     headerType: 3,
>     documentMessage: media.message.documentMessage
> ```
> 
> Send buttons with video:
> 
> ```ts
>     headerType: 5,
>     videoMessage: media.message.videoMessage
> ```
> 
> Send buttons with location:
> 
> ```ts
>     headerType: 6,
>     locationMessage: media.message.locationMessage
> ```

Very very tnx 🙂

**Comment by Denver1997** [comment]
How to send link able button messages for Call or Visit Website

**Comment by CyberDraco** [comment]
Bailay err.come

**Comment by CyberDraco** [comment]
Pls help me

**Comment by Cloud-Dark** [comment]
image
my script not display error, but my node js like freeze after send button message
can you help me?

**Comment by joaopaulosobral** [comment]
> my script not display error, but my node js like freeze after send button message
> can you help me?

it achieved?

**Comment by joaopaulosobral** [comment]
> How to send link able button messages for Call or Visit Website

it achieved?

**Pull request merged**
