### PR TITLE
working tempelate message in whatsapp

### PR DESCRIPTION
**Pull request by FERDIZ-afk**

### CODE REVIEW

**Comment by FERDIZ-afk** [comment]
Screenshot_2022-09-19-09-33-47-40_7352322957d4404136654ef4adb64504


Plis pull me code

**Review by azudindaem — COMMENTED** [review]
Please do not submit PR for this. 

#2101 
#2098 
#1996 

and more..

Kindly delete this PR thanks

**Comment by FERDIZ-afk** [comment]
> Please do not submit PR for this.
> 
> #2101 #2098 #1996
> 
> and more..
> 
> Kindly delete this PR thanks

why is this homework not resolved on whatsapp it doesn't appear, but after changing the part it is visible. is Baileys lazy to change the code?

**Comment by azudindaem** [comment]
Please search through the repo before creating new PRs & issues..  not working on ios device..

**Comment by FERDIZ-afk** [comment]
Android users are also confused if it won't appear paste messages on Android

**Comment by FERDIZ-afk** [comment]
I also understand what it feels like to use iOS users

**Pull request closed without merging**
