### PR TITLE
GitHub Actions integration

### PR DESCRIPTION
**Pull request by AZMCode**
The repo will now automatically put the typedoc results in the `gh-pages` branch of the repo.
A new push to master will result in a new Release with a release asset to match and, if the `NPM_TOKEN` secret is set will also upload the package to npm. Fulfills #111 

Note: Could not test the jobs that relied on a push to master, for obvious reasons.

### CODE REVIEW

**Comment by adiwajshing** [comment]
Looks really good, thanks a lot for this! If I set the `NPM` token, it'll publish to NPM on every commit?

**Comment by AZMCode** [comment]
It should publish to NPM on push to master. The secret is `NPM_TOKEN`
Please consider this was done rather quickly, and the push to master might not work just yet. I'm trying to find a way to test it. Otherwise, the `Test` job works.

**Comment by AZMCode** [comment]
Nope, automated testing is broken. Since the program requires logging into Whatsapp to test, we can't run it automatically
We could store the session keys in the secrets, but then that'd mean having a dedicated phone just for CI

**Comment by AZMCode** [comment]
Forgot to mention, this PR creates a new release and uploads a package to it every time there's a push to master.

**Comment by AZMCode** [comment]
Nope, PR is broken rn. Just tested it and it didnt run the publishing jobs

**Comment by AZMCode** [comment]
Alright, I've tested it a bit more on my fork, and it all seems to work.

**Comment by adiwajshing** [comment]
So, I'm going to include this for Baileys 3.0, is there a way to not release with every push?

**Comment by AZMCode** [comment]
I believe it is possible to remove the "push" trigger, and then manually execute the workflow when needed.
Might give it a go.

**Comment by AZMCode** [comment]
Done. Workflow will now only work when manually activated. Under `Actions`->`CI`->`Run Workflow`

**Comment by adiwajshing** [comment]
Merged, thanks a lot @AZMCode

**Comment by adiwajshing** [comment]
@AZMCode so, the publish package is still called on every push causing the workflow to be marked as failed. Can you see what's up?

**Comment by AZMCode** [comment]
Oh lord. it doesn't name the release correctly.
Debugging on master sounds like a not fun time.

**Comment by AZMCode** [comment]
Already made a new PR which hopefully should fix all these issues.

**Pull request merged**
