### PR TITLE
Query update

### PR DESCRIPTION
**Pull request by PouyaAklion**
actually, my problem was loading messages that were sent today in a group so I wrote two new methods at MessagesExtra.ts.

Hoping to be accepted 😊

thank you

### CODE REVIEW

**Comment by adiwajshing** [comment]
I apologise for not making this clear enough, but Baileys has a generic function to load all messages fitting your criteria. It's called `findMessage` & you can use it like this for your purpose with only a few lines of code:
``` ts

    await conn.connect()

    const isToday = (someDate: Date) => {
        const today = new Date()
        return someDate.getDate() == today.getDate() &&
            someDate.getMonth() == today.getMonth() &&
            someDate.getFullYear() == today.getFullYear()
    }
    const todayMessages = []
    conn.findMessage(
        '1234@s.whatsapp.net', 
        20, 
        msg => isToday(new Date(toNumber(msg.messageTimestamp)*1000)) && todayMessages.push(msg) && true)

```

**Comment by itacirgabral** [comment]
there is `messagesReceivedAfter`

https://github.com/adiwajshing/Baileys/blob/84edfe1ca0b4b5482cd5d923b4d16b8034aba71b/src/WAConnection/7.MessagesExtra.ts#L196-L216

**Comment by PouyaAklion** [comment]
I am using [https://www.npmjs.com/package/baileys](Baileys npm package) it doesn't seem to be the same as Github.

**Comment by PouyaAklion** [comment]
I am using [Baileys npm package](https://www.npmjs.com/package/baileys) it doesn't seem to be the same as Github.

**Comment by itacirgabral** [comment]
> I am using [Baileys npm package](https://www.npmjs.com/package/baileys) it doesn't seem to be the same as Github.

Vanilla hat v1.1.1 https://www.npmjs.com/package/baileys
Red hat v3.3.1 https://www.npmjs.com/package/@adiwajshing/baileys

Could be interesting Baileys have an addon system. Maybe `7.MessagesExtra.ts` could be all in the `@adiwajshing/baileysAddonMessagesExtra` addon.

**Pull request closed without merging**
