### PR TITLE
Added method to block/unblock user (close #233)

### LINKED ISSUE #233: How to block or unblock a user?
Hi,

I looked doc, code and whatsapp-web-reg but i didn't find anything.
How to block or unblock a user?

### PR DESCRIPTION
**Pull request by edgardmessias**
Added method to block or unblock user
Added event for blocklist changes

To test (it takes a while): `npm install github:edgardmessias/Baileys#block_user`

### CODE REVIEW

**Comment by Quiec** [comment]
@adiwajshing Please merge it

**Comment by adiwajshing** [comment]
@edgardmessias thanks a lot for this. Can you please add a test for this function? 

I'll merge then.

**Comment by edgardmessias** [comment]
@adiwajshing , I added the tests and I created an event

**Comment by Quiec** [comment]
@adiwajshing When exactly will you release?

**Comment by adiwajshing** [comment]
You can use the latest commit for now. Let's wait a while before a release to NPM

**Comment by Quiec** [comment]
@adiwajshing Not working with github in Heroku. NPM I have to wait.

**Pull request merged**
