### PR TITLE
update WA version

### PR DESCRIPTION
**Pull request by bluej4ker**

### CODE REVIEW

**Comment by frmdeveloper** [comment]
Actually it's not important. Because automatic updates are available
```js
const { version, isLatest } = await fetchLatestBaileysVersion()
let sock = makeWASocket({
    auth: state,
    version,
    logger: P({ level: 'silent' })
      
    etc.
```

**Comment by Darker935** [comment]
WOW YOU'RE GENIOUS LOL!!!
Big Change!!! Amazing!!!

**Comment by HUGEIT** [comment]
> WOW YOU'RE GENIOUS LOL!!! Big Change!!! Amazing!!!

don't insult him like that. if the versions don't update, it will refuse to connect. the PR is valid.

**Comment by frmdeveloper** [comment]
fetchLatestWaWebVersion

**Comment by mzayn** [comment]
the version was update for v2.2232.8 ?

**Pull request merged**
