### PR TITLE
feat: get latest version from whatsapp

### PR DESCRIPTION
**Pull request by gandol**
get latest version from whatsapp endpoint and implement it on exaple.ts

### CODE REVIEW

**Comment by viniciusgdr** [comment]
It's probably not a good idea as there might be some code change in WhatsApp Web and some errors might occur.

**Review by viniciusgdr — COMMENTED** [review]
It would not need to add a new dependency, it could be done with the "got" normally

**Comment by HUGEIT** [comment]
the idea is cool but on a protocol change this will fuck up everything. I vote against merging this

**Comment by gandol** [comment]
> It's probably not a good idea as there might be some code change in WhatsApp Web and some errors might occur.

it just optional I just create the function and implementation for this function is an example file, based on my current project i can't log in because just an old version

**Comment by burstfreeze** [comment]
> it just optional

Except in your code it is not.

It is too risky and could result in unexpected behavior like feedback loops that could unnecessarily spam the server with requests which is exactly what we don't want to do since we want to play fair here. We are only guests on their system so we have to behave like guests and don't put excessive load on their service.

**Comment by gandol** [comment]
> > it just optional
> 
> Except in your code it is not.
> 
> It is too risky and could result in unexpected behavior like feedback loops that could unnecessarily spam the server with requests which is exactly what we don't want to do since we want to play fair here. We are only guests on their system so we have to behave like guests and don't put excessive load on their service.

its true if the code for the checking inside loop or inside incomming message listener, but if the code just run once on try to login i think its a normal and the whatsapp web is using this method
image

**Comment by burstfreeze** [comment]
No this is not what it's about. Let's say version 3.0.1 has a different handshake message and will close the connection on Baileys' attempt to connect, it will turn into an indefinite loop.

**Comment by gandol** [comment]
> No this is not what it's about. Let's say version 3.0.1 has a different handshake message and will close the connection on Baileys' attempt to connect, it will turn into an indefinite loop.

hmmm i seee, if the code was merged and used on production will break all

**Pull request closed without merging**
