### PR TITLE
[MD] Make log "saving auth state" optional

### PR DESCRIPTION
**Pull request by guiguicdd**
This will make the console cleaner in large groups. Where this function run multiple times in order to check each member pre-key

### CODE REVIEW

**Comment by mateuscdor** [comment]
just change the logger parameter: pin

é só alterar o parâmetro do logger: pino

**Comment by guiguicdd** [comment]
const sock = makeWASocket({ printQRInTerminal: true, auth: state })

That is how my makeWASocket is. Do I need to insta pino?

Assim que está o makeWASocket. Devo instalar o pino?

**Comment by mateuscdor** [comment]
me chama no whats  73 9 9177-6616

**Review by guiguicdd — COMMENTED** [review]
sets logs as true by default

**Pull request closed without merging**
