### PR TITLE
List and template bug fix

### PR DESCRIPTION
**Pull request by maulalwi**
I tried to get rid of the uncommentment in the script and the script ran normally again

### CODE REVIEW

**Comment by FatihArridho** [comment]
Thx

**Comment by marcelo386** [comment]
iOS not work yet

**Comment by mmhospedagem** [comment]
templatesButton not send

**Comment by marcelo386** [comment]
IMG-20220804-WA0012

iOS not working 
Android is OK

**Comment by adrianokelvio** [comment]
TemplatesButton not working correctly WhatsApp .75 (new version)

Simple buttons message is working Listmessage too!

**Comment by pandigresik** [comment]
work for me
Thanks

**Comment by vyxxr** [comment]
works perfectly for me

**Comment by enoksaju** [comment]
this solve on android , but crash the chat on iphone latest version

**Comment by brokeboienige** [comment]
hydratedTemplate is not working for me

**Comment by prototypeninja** [comment]
how to make the changeion in javascript version

**Comment by BlackAmda** [comment]
working perfectly

**Comment by marcelo386** [comment]
iOS not Working version APP 2.22.15.77
APP Crash Button

List is Working

**Review by Manjit2003 — APPROVED** [review]

**Review by BlackAmda — APPROVED** [review]

**Comment by PurpShell** [comment]
@adiwajshing

**Review by PurpShell — APPROVED** [review]
tested, working

**Comment by amiruldev20** [comment]
why hydrate messages can't be seen in some whatsapp ori on different devices?

**Comment by adiwajshing** [comment]
this patch only works on some devices and not others, since it's not a 100% fix -- I commented those lines out when I pushed & won't merge this PR till we have a fix that works for everyone

**Comment by jefaokpta** [comment]
Guys I've tested and give this results:
Using a IOS, send message button to a IOS, works ok.
Using a Android, send message button to a Android, works ok, but IOS not work.

**Comment by ricocrivelli** [comment]
@jefaokpta any suggestion how to fix this?

**Comment by jefaokpta** [comment]
I'm sorry, I'm not to able to help. I just wanted contrib with data.

**Pull request closed without merging**
