### PR TITLE
Fix baileys install through github

### PR DESCRIPTION
**Pull request by PurpShell**
There is an issue while installing Baileys through github (`yarn add github:adiwajshing/Baileys` or `yarn add git+https://github.com/adiwajshing/Baileys`), where the prepare script fails the typescript compile due to missing types in dependencies.. (mainly keyed-db and @types/ws)

this ensures all modules are installed, though using yarn or npm is up to debate..

### CODE REVIEW

**Comment by PurpShell** [comment]
Tf happened to the linter

**Comment by fadiinho** [comment]
This not works. The `prepare` script runs on `yarn install`, so if you make `prepare` execute `yarn install`, this will be an infinity loop. You can see it [here](https://docs.npmjs.com/cli/v8/using-npm/scripts#life-cycle-scripts): `Runs on local npm install without any arguments`
image

**Comment by PurpShell** [comment]
> 

hmm

**Comment by fadiinho** [comment]
I guess I just discovered the solution.
I was reading the Baileys `package.json` and noticed that tsc was not a dev dependency.
As you can read [here](https://docs.npmjs.com/cli/v7/using-npm/scripts#life-cycle-scripts):
`NOTE: If a package being installed through git contains a prepare script, its dependencies and devDependencies will be installed, and the prepare script will be run, before the package is packaged and installed.`
So yarn tries to run `tsc` but isn't installed. Maybe if add tsc as a dev dependency it will work.

**Comment by PurpShell** [comment]
> I guess I just discovered the solution.
> I was reading the Baileys `package.json` and noticed that tsc was not a dev dependency.
> As you can read [here](https://docs.npmjs.com/cli/v7/using-npm/scripts#life-cycle-scripts):
> `NOTE: If a package being installed through git contains a prepare script, its dependencies and devDependencies will be installed, and the prepare script will be run, before the package is packaged and installed.`
> So yarn tries to run `tsc` but isn't installed. Maybe if add tsc as a dev dependency it will work.

tsc means typescript compile, it is found in the "typescript" package

**Pull request closed without merging**
