### PR TITLE
Removing messages from msgRetryMap

### PR DESCRIPTION
**Pull request by Alhar6i**
The current logic deletes messages if the retry counter is greater than or equal to 5 which means that if the retry succeeded before reaching this threshold the message won't be deleted and the msgRetryMap will keep growing up.
Here we remove message ids from "msgRetryMap" if they have been successfully sent.

### CODE REVIEW

**Comment by Alhar6i** [comment]
make the AxiosRequestConfig parameter optional in fetchLatestWaWebVersion

**Comment by Alhar6i** [comment]
@adiwajshing any comments on this PR?

**Comment by adiwajshing** [comment]
1. This doesn't account for the fact that different devices of the same user may not have received the message correctly -- only one device did
2. This clearly hasn't been tested, because msgRetryMap keys using `participant + id` not just `id`. So even via this PR, it won't do anything

**Comment by Alhar6i** [comment]
Ok, many thanks

**Pull request closed without merging**
