### PR TITLE
[MD] Added template support and footers for buttons & templates

### PR DESCRIPTION
**Pull request by PurpShell**
self-explanatory. 

Usage:

```ts
sock.sendMessage(to, {templateButtons: [ {index: 1, urlButton: {displayText: 'Star Baileys on GitHub!', url: 'https://github.com/adiwajshing/Baileys'}}, {index: 2, callButton: {displayText: 'Call them cops!', phoneNumber: '911'}}, {index: 3, quickReplyButton: {displayText: 'Just a good old reply', id: 'reply-1'}} ], footer: 'any footer'})
```

### CODE REVIEW

**Comment by adiwajshing** [comment]
Looks solid to me, just need some additional doc on the readme

**Comment by PurpShell** [comment]
> Looks solid to me, just need some additional doc on the readme

done

**Comment by ThisMe124** [comment]
Omg

**Comment by amichaan** [comment]
Sorry sirl I've tried sending template messages with images, but the image is not appear, it just a button and text only

**Comment by gamerashi** [comment]
image
image

**Comment by PurpShell** [comment]
should be fixing soon.

**Pull request merged**
