### PR TITLE
Emit event for true timestamp on retried messages as well instead of basically only emitting the current date.

### PR DESCRIPTION
**Pull request by burstfreeze**
https://github.com/adiwajshing/Baileys/issues/868

### CODE REVIEW

**Comment by adiwajshing** [comment]
Can't you get the exact same amount of info from `messages.upsert`?

**Comment by burstfreeze** [comment]
@adiwajshing this is what I have explained in the comments in the issue, nowhere does Baileys emit the real timestamp. You think someone would need the wrong timestamp, which is why I have added this event now so you can keep the bad one and everyone who needs the real one can listen to the new event.

**Comment by adiwajshing** [comment]
Why wouldn't this work @burstfreeze ?

``` ts
const retriedMsgsTimestamps: { [_: string]: number } = { } 
ev.on('messages.upsert', ({ messages: [msg] }) => {
  if(msg.messageStubType === WAMessageStubType.CIPHERTEXT) }
    // store original timestamp
    retriedMsgsTimestamps[msg.key.id] = msg.timestamp
  } else {
    // restore original timestamp
    if(retriedMsgsTimestamps[msg.key.id]) msg.timestamp =  retriedMsgsTimestamps[msg.key.id]
  }  
})

```

**Comment by burstfreeze** [comment]
Maybe I misunderstand something but in the `messages.upsert` I get output like this: 

`{"messages":[{"key":{"remoteJid":"123-123@g.us","fromMe":false,"id":"ABC","participant":"123@s.whatsapp.net"},"messageStubType":"CIPHERTEXT","messageStubParameters":["No sender key for: 123-123@g.us::123::0"]}],"type":"append"}`

which does not seem to include timestamps

**Comment by adiwajshing** [comment]
That's my bad then @burstfreeze, this should resolve it:

https://github.com/adiwajshing/Baileys/pull/696/commits/d2e3abfe49088777dcd20256be7f282868957638

**Comment by burstfreeze** [comment]
Thank you so much for your availability @adiwajshing this looks correct.

**Pull request closed without merging**
