### PR TITLE
fix sendReadReceipt()

### PR DESCRIPTION
**Pull request by barkerpedro**
I don't know if it's correct, but to fix the problem with the ".sendReadReceipt()" function when changing the status of a message received without internet on the cell phone.
As reported in #994

connected to internet:
Screenshot_4

disconnected on internet:
Screenshot_5

### CODE REVIEW

**Comment by mateuscdor** [comment]
Fixed the problem, thanks for this pull
@barkerpedro

**Comment by burstfreeze** [comment]
While this may work, it looks like it's overriding the client's privacy preferences since you somewhat invalidate the whole if statement.

From what you are writing it looks like this is not a matter of A or B depending on the setting but rather an A/B +C or even +C+D when offline, basically introducing one or more states depending on offline status additionally to the privacy status.

**Comment by adiwajshing** [comment]
I agree with @burstfreeze why aren't privacy settings being respected?

**Comment by barkerpedro** [comment]
> I agree with @burstfreeze why aren't privacy settings being respected?

Test it out by changing your privacy settings.

**Comment by viniciusgdr** [comment]
Even changing it wouldn't make sense. Since you're disrespecting your privacy settings

Also, you made a case, which would be unnecessary as it would return everything the same. Like @burstfreeze mentioned

**Comment by viniciusgdr** [comment]
> Even changing it wouldn't make sense. Since you're disrespecting your privacy settings
> 
> Also, you made a case, which would be unnecessary as it would return everything the same. Like @burstfreeze mentioned

I use this feature and it's working properly.

**Comment by barkerpedro** [comment]
> > Even changing it wouldn't make sense. Since you're disrespecting your privacy settings
> > Also, you made a case, which would be unnecessary as it would return everything the same. Like @burstfreeze mentioned
> 
> I use this feature to read chats and it is working correctly.

But are you reading chats when your cell phone has no internet connection?

**Comment by barkerpedro** [comment]
It's not really respecting the privacy settings. What would be the solution?

**Comment by viniciusgdr** [comment]
> > > Even changing it wouldn't make sense. Since you're disrespecting your privacy settings
> > > Also, you made a case, which would be unnecessary as it would return everything the same. Like @burstfreeze mentioned
> > 
> > 
> > I use this feature to read chats and it is working correctly.
> 
> But are you reading chats when your cell phone has no internet connection?

no.

From what I've seen here, it's just reversing the order of privacy.

**Comment by frmdeveloper** [comment]
What privacy do you mean?
I don't understand 😁😁

**Comment by viniciusgdr** [comment]
This Correction has already been made by @lyfe00011 . The sendReadReceipt has probably already been resolved

**Comment by barkerpedro** [comment]
No change required, fixed issue with correcting privacy settings in #1037

**Pull request closed without merging**
