### PR TITLE
Add option to distinguish between join group types.

### PR DESCRIPTION
**Pull request by Schwartzblat**

### CODE REVIEW

**Review by azudindaem — APPROVED** [review]
thanks

**Comment by adiwajshing** [comment]
I think you can just listen for `messages.upsert` and use the stub type from that to accomplish what you're trying to do. There isn't a need to modify the baileys source for that

**Comment by Schwartzblat** [comment]
I can do it but it less comfortable and it makes more sense to add it to group-participants.update.
It's not changing anything only makes group-participants.update event more usable.

**Comment by adiwajshing** [comment]
I don't think adding a "messageStubType" is a good idea for the "group-participants.update" event

**Comment by Schwartzblat** [comment]
Why not? It gives more information on the event and explained what cause this change.

**Pull request closed without merging**
