### PR TITLE
fix for item-not-found, when user does not have a profile picture set

### PR DESCRIPTION
**Pull request by panalgin**
Hi, regarding a stale issue #1622 

When the current user has no profile picture set, profilePictureUrl function triggers a "Boom" error upon receiving "item-not-found" response from the WA servers and this terminates the execution, since this Boom crash can not be caught or bypassed from the client code, I had to make this modification 

Because having a "null profile picture url" is not a fatal error, the **assetNodeErrorFree** function should bypass this error, instead of throwing a Boom-type crash.

Below is a simple fix, and I don't think it will affect anywhere on the project where "item-not-found" error should be regarded as a fatal crash.

Please feel free to comment and suggest fixes

### CODE REVIEW

**Comment by adiwajshing** [comment]
Why not just:
```
sock.getProfilePicture(jid).catch(() => null)
```

The Boom is there so someone could distinguish between the errors, like 404s, 403s & 401s

**Comment by panalgin** [comment]
> Why not just:
> 
> ```
> sock.getProfilePicture(jid).catch(() => null)
> ```
> 
> The Boom is there so someone could distinguish between the errors, like 404s, 403s & 401s

This doesn't work, the execution halts and node process gets killed immediately

**Comment by panalgin** [comment]
Sorry it is my bad, seems like try catch block doesn't work but, using .catch directly worked, now it catches the boom. You can disregard this pull request, it's my poor TS skills 🤣

```TypeScript
              try {
                sock.profilePictureUrl(sock.user!.id, "image", 5000).then((url: string | undefined) => {
                  console.log("Pic: " + url);
                }).catch((error) => {
                  console.log("This gets caught");
                });
              }
              catch (error) {
                  console.log("This won't get caught");
              }

**Comment by vienapps** [comment]
> Sorry it is my bad, seems like try catch block doesn't work but, using .catch directly worked, now it catches the boom. You can disregard this pull request, it's my poor TS skills 🤣
> 
> ```ts
>               try {
>                 sock.profilePictureUrl(sock.user!.id, "image", 5000).then((url: string | undefined) => {
>                   console.log("Pic: " + url);
>                 }).catch((error) => {
>                   console.log("This gets caught");
>                 });
>               }
>               catch (error) {
>                   console.log("This won't get caught");
>               }
> ```

How To convert To  Extension .js Sir....?

**Pull request closed without merging**
