### PR TITLE
feat: Added group notification: change description

### PR DESCRIPTION
**Pull request by LeonardoBein**
This PR adds in parameter notification description when value is updated.

### CODE REVIEW

**Comment by LeonardoBein** [comment]
@adiwajshing, you can see it ?

**Review by azudindaem — APPROVED** [review]
Tested ok

**Review by BlackAmda — APPROVED** [review]
Worked 👍🏻

**Review by zennn08 — APPROVED** [review]

**Comment by LeonardoBein** [comment]
3 reviewers approved this PR. @adiwajshing you can merge ?

**Comment by LeonardoBein** [comment]
Please do not close this PR.

**Comment by victor-nunesm** [comment]
Worked here too. Any change of merging this PR?

**Review by arugaz — APPROVED** [review]

**Comment by LeonardoBein** [comment]
.

**Pull request closed without merging**
