### PR TITLE
Added support for send list message

### PR DESCRIPTION
**Pull request by ibnusyawall**
added a list of Message types to messages flow, looks like this is needed 3>

use:

```js
conn.sendMessage(jid, { buttonText: string, description: string, listType: 1, title: string, sections: ISections[] }, MessageType.listMessage)
```

[ISections[]](https://adiwajshing.github.io/Baileys/interfaces/proto.isection.html) 

screenshot:
IMG-20210708-WA0661
IMG-20210708-WA0662

thanks.

### CODE REVIEW

**Comment by vasani-arpit** [comment]
I believe this is expansion to #574

**Comment by ibnusyawall** [comment]
> I believe this is expansion to #574

but this commit is shown for supported on message flow sendMessage method with type list message xD

**Comment by ekoeryanto** [comment]
mantap!

@adiwajshing release it, please

**Comment by azudindaem** [comment]
testing from normal whatsapp to any number successful. but from business account its failed

**Comment by Dvnz99** [comment]
i can't understand, please teach me, wa.me/628885960825

**Comment by diosamuel** [comment]
> testing from normal whatsapp to any number successful. but from business account its failed

me too

**Pull request merged**
