### PR TITLE
Fixed Cannot read property 'key' of undefined

### PR DESCRIPTION
**Pull request by ilyaborodin**
Messages can be empty. I added logger and check this.

Снимок экрана 2021-11-18 в 23 29 07

So I added a condition to avoid the error

#874

### CODE REVIEW

**Review by PurpShell — APPROVED** [review]

**Comment by adiwajshing** [comment]
messages should never be empty, this is solving the symptom not the actual cause of the problem.
Also I think I resolved this issue in a previous commit.

**Comment by canove** [comment]
@adiwajshing, found a consistent way to reproduce this. 

You need to start two connections at the same time. If connection ONE sends a message to connection TWO, this error will throw.

Adding a `if !messages[0] return` immediately "resolves" it. But, as you pointed, we better find the cause.
```
 ev.on('messages.upsert', async ({ messages }) => {
        if (!messages[0]) {
          console.log("Messages array", messages)
          return;
        }
        var _a;
        const chat = { id: messages[0].key.remoteJid };
        const contactNameUpdates = {};
```

The messages array has no messages...
image

**Comment by HUGEIT** [comment]
what you describe this may be an explanation for https://github.com/adiwajshing/Baileys/pull/833#issuecomment-968364048 that I ran into and maybe the cause or related is https://github.com/adiwajshing/Baileys/issues/870

**Comment by adiwajshing** [comment]
Thanks. It's odd, I didn't know sending a stanza with 0 messages is possible -- I've added a patch accounting for it now:

https://github.com/adiwajshing/Baileys/pull/696/commits/27cf3954e8926313153d5be87b057770f6408842

**Comment by HUGEIT** [comment]
> Thanks. It's odd, I didn't know sending a stanza with 0 messages is possible -- I've added a patch accounting for it now:

@adiwajshing have you had a case where this visibly happened + the log for it? if not, I know it sounds invasive but what do you think of anonymous telemetry for baileys? or would it be too hard to remove personal information for unhandled objects? Or just a few characters and then go up from there? just a few ideas..

**Pull request closed without merging**
