### PR TITLE
[MD] Fixing unused variables and using the example.ts as a visible example

### PR DESCRIPTION
**Pull request by Dakauann**
Making the connection variable more explicit on the example code.

### CODE REVIEW

**Comment by burstfreeze** [comment]
For the time being I actually prefer `sock` for MD and `conn` for legacy since it for now offers a more clear difference that is easier to spot. But in itself everything should be consistent

**Comment by Dakauann** [comment]
> For the time being I actually prefer `sock` for MD and `conn` for legacy since it for now offers a more clear difference that is easier to spot. But in itself everything should be consistent

Normally on a real time coding i use this way to connect, and theres no problems, so i did this pull request to make It clean

**Comment by adiwajshing** [comment]
So just copying the entire example script into the readme?

**Comment by Dakauann** [comment]
> So just copying the entire example script into the readme?

Of course ;>

**Comment by Dakauann** [comment]
> So just copying the entire example script into the readme?

I had just changed the socks in the example to conn, (the way I make the connection) but then I remembered the example, and found it more explanatory to use, it's up to you.

**Pull request closed without merging**
