### PR TITLE
ephemeral key is invalid. Valid key is expiration

### PR DESCRIPTION
**Pull request by sudomaaz**

### CODE REVIEW

**Comment by sudomaaz** [comment]
in the function groupToggleEphemeral since to pass ephemeral information the key "ephemeral" is used which is invalid and results in 408 timeout. The valid key to pass is "expiration". tested and verified on local.

**Comment by sudomaaz** [comment]
Issue reported due to this 

https://github.com/adiwajshing/Baileys/issues/1387

**Comment by HUGEIT** [comment]
can you check whether this still works in legacy? just making sure we don't break things

**Comment by sudomaaz** [comment]
> can you check whether this still works in legacy? just making sure we don't break things

Yes key ephemeral still works in legacy its only changed to expiration in MD

**Comment by HUGEIT** [comment]
just realized there is a different src folder for legacySocket 
in that case it's probably a very nice pr, I think it will be merged

**Pull request merged**
