### PR TITLE
Add Example of Redis Session Store Implementation

### PR DESCRIPTION
**Pull request by slaveofcode**
This PR will add an example of session storage with Redis and update the documentation. 

The implementation includes
1. Create new session data to redis if not exist (based on key `myWAKey`)
2. Recover session data from redis if exist
3. Delete session data on redis if device removed from phone.

### CODE REVIEW

**Comment by adiwajshing** [comment]
Appreciate the effort, but a couple things:
1. redis should be a peer dependency
2. you're serialising & saving the entire auth state every time something is updated. Highly inefficient & will cause your server to be out of compute power really fast. Instead, save only the item that is being updated (passed in the `set` function of the `SignalKeyStore`)
3. Do not override with `any`

**Comment by tarikhagustia** [comment]
> Appreciate the effort, but a couple things:
> 
> 1. redis should be a peer dependency
> 2. you're serialising & saving the entire auth state every time something is updated. Highly inefficient & will cause your server to be out of compute power really fast. Instead, save only the item that is being updated (passed in the `set` function of the `SignalKeyStore`)
> 3. Do not override with `any`

hi @adiwajshing , i took on your example auth state its store many things that make session file is huge if we have many chat history and contact. 
i plan to make own custom session handler but my question is the all things in session file are needed to restore the session? i saw some data like broadcast info in session file

**Comment by adiwajshing** [comment]
You only need to save/load the keys passed in the load/save method -- the full session never needs to be loaded/saved at once

**Comment by ycarooliveira** [comment]
@adiwajshing Can you elaborate a bit more about what you said? I always thought we should save everything as you did at the json file

**Comment by clairton** [comment]
Hi, is this sample ok?
```ts
import { BufferJSON, initAuthCreds, proto, AuthenticationCreds, AuthenticationState, SignalDataTypeMap } from '@adiwajshing/baileys'
import { join } from 'path'
import Redis from 'ioredis'

export const useRedisAuthState = async (redisUrl: string, baseKey: string, token: string): Promise<{ state: AuthenticationState, saveCreds: () => Promise<any> }> => {
  const redis = new Redis(redisUrl)

  const writeData = (data: any, key: string) => {
    return redis.set(join(baseKey, token, fixKeyName(key)!), JSON.stringify(data, BufferJSON.replacer))
  }

  const readData = async (key: string) => {
    try {
      const data = await redis.get(join(baseKey, token, fixKeyName(key)!))
      if (data) {
        return JSON.parse(data, BufferJSON.reviver)
      }
    } catch (error) {
      return null
    }
  }

  const removeData = async (key: string) => {
    try {
      await redis.del(join(baseKey, token, fixKeyName(key)!))
    } catch {

    }
  }

  const fixKeyName = (key?: string) => key?.replace(/\//g, '__')?.replace(/:/g, '-')

  const creds: AuthenticationCreds = await readData('') || initAuthCreds()

  return {
    state: {
      creds,
      keys: {
        get: async (type, ids) => {
          const data: { [_: string]: SignalDataTypeMap[typeof type] } = {}
          await Promise.all(
            ids.map(
              async id => {
                let value = await readData(`${type}-${id}`)
                if (type === 'app-state-sync-key' && value) {
                  value = proto.Message.AppStateSyncKeyData.fromObject(value)
                }

                data[id] = value
              }
            )
          )

          return data
        },
        set: async (data) => {
          const tasks: Promise<any>[] = []
          for (const category in data) {
            for (const id in data[category]) {
              const value = data[category][id]
              const key = `${category}-${id}`
              tasks.push(value ? writeData(value, key) : removeData(key))
            }
          }

          await Promise.all(tasks)
        }
      }
    },
    saveCreds: () => {
      return writeData(creds, '')
    }
  }
}
```

**Comment by morganzysman** [comment]
Hi,

I

> Hi, is this sample ok?
> 
> ```ts
> import { BufferJSON, initAuthCreds, proto, AuthenticationCreds, AuthenticationState, SignalDataTypeMap } from '@adiwajshing/baileys'
> import { join } from 'path'
> import Redis from 'ioredis'
> 
> export const useRedisAuthState = async (redisUrl: string, baseKey: string, token: string): Promise<{ state: AuthenticationState, saveCreds: () => Promise<any> }> => {
>   const redis = new Redis(redisUrl)
> 
>   const writeData = (data: any, key: string) => {
>     return redis.set(join(baseKey, token, fixKeyName(key)!), JSON.stringify(data, BufferJSON.replacer))
>   }
> 
>   const readData = async (key: string) => {
>     try {
>       const data = await redis.get(join(baseKey, token, fixKeyName(key)!))
>       if (data) {
>         return JSON.parse(data, BufferJSON.reviver)
>       }
>     } catch (error) {
>       return null
>     }
>   }
> 
>   const removeData = async (key: string) => {
>     try {
>       await redis.del(join(baseKey, token, fixKeyName(key)!))
>     } catch {
> 
>     }
>   }
> 
>   const fixKeyName = (key?: string) => key?.replace(/\//g, '__')?.replace(/:/g, '-')
> 
>   const creds: AuthenticationCreds = await readData('') || initAuthCreds()
> 
>   return {
>     state: {
>       creds,
>       keys: {
>         get: async (type, ids) => {
>           const data: { [_: string]: SignalDataTypeMap[typeof type] } = {}
>           await Promise.all(
>             ids.map(
>               async id => {
>                 let value = await readData(`${type}-${id}`)
>                 if (type === 'app-state-sync-key' && value) {
>                   value = proto.Message.AppStateSyncKeyData.fromObject(value)
>                 }
> 
>                 data[id] = value
>               }
>             )
>           )
> 
>           return data
>         },
>         set: async (data) => {
>           const tasks: Promise<any>[] = []
>           for (const category in data) {
>             for (const id in data[category]) {
>               const value = data[category][id]
>               const key = `${category}-${id}`
>               tasks.push(value ? writeData(value, key) : removeData(key))
>             }
>           }
> 
>           await Promise.all(tasks)
>         }
>       }
>     },
>     saveCreds: () => {
>       return writeData(creds, '')
>     }
>   }
> }
> ```

Hi, have you had luck with this implemtation ?

Regards

**Comment by morganzysman** [comment]
Why does the set function update in the sender-key value  category profile images.
I'm confused if we are indeed only saving the requiered information.

Regards

**Pull request closed without merging**
