### PR TITLE
Multi Device Support

### PR DESCRIPTION
**Pull request by adiwajshing**
This is still very early. Won't be merged anytime soon.

### CODE REVIEW

**Comment by PurpShell** [comment]
https://github.com/adiwajshing/Baileys/tree/multi-device#writing-custom-functionality is outdated, battery info is gone

**Comment by hasanbasri1993** [comment]
amazing

**Comment by algoz098** [comment]
Woo woo

**Comment by frmdeveloper** [comment]
wow, scrape whatsapp web from scratch again

**Comment by frmdeveloper** [comment]
hard to use

**Comment by viniciusgdr** [comment]
Screenshot_1

hey, there are two "participant" in the "messages.upsert" listener, will it be fixed?

Example:
conn.ev.on('messages.upsert', async m => {
console.log(m.messages[0])
})

**Comment by frmdeveloper** [comment]
I can't import this module in javascript using "require()"

anyone can teach me?

**Review by frmdeveloper — COMMENTED** [review]
ttt

**Pull request merged**
