### PR TITLE
📱 Add Video/Image Resolution Metadata using FFprobe

### PR DESCRIPTION
**Pull request by Nurutomo**
## Changes
1. `MessageOptions`:
   - media `width`
   - media `height`

2. `package.json`:
   - `ffprobe` package
   
3. `Utils.ts`:
   - `extractMediaMessage`
   ```ts
   extractMediaMessage(file: string, ffprobePath?: string) => Promise<ffprobe.FFProbeResult>
   ```
   
   
#### WhatsApp Android
WhatsApp Android
#### WhatsApp Web
WhatsApp Web

### CODE REVIEW

**Comment by jeremia49** [comment]
Good PR, but I think you need to also include ffprobe-static , in case the system hasn't installed ffprobe yet.

IMO, I don't think we need this PR , because it's only make small difference. At same time, considering we need to depends on some binary build that may not exists or works in some system. 

I think one can make themselves if they want to. CMIIW

**Comment by Nurutomo** [comment]
Sorry about `0.Base.ts`, I pressed `Alt + Shift + F` there
https://github.com/adiwajshing/Baileys/pull/507/files#diff-ee3806277def7f3d927ae861e384827fbcd3afc829c6b91324fde4cd10c7d24b

**Comment by Nurutomo** [comment]
Changes:

image

**Comment by Nurutomo** [comment]
i dont know how does `streamingSidecar` actually generated

**Comment by moskoweb** [comment]
Why wasn't it merged?

**Pull request closed without merging**
