### PR TITLE
Changing getDevice shapes

### PR DESCRIPTION
**Pull request by kauanzito**
med I bring an "explanation"nces between OS, and I bring an "explanation"

### CODE REVIEW

**Comment by viniciusgdr** [comment]
has no reason to change the answers, it could break codes that depend on this function

**Comment by kauanzito** [comment]
> has no reason to change the answers, it could break codes that depend on this function

well, it will be more explanatory that way, and not to mention that it will be easier to understand. A user might get confused by getting their deviceType as "web" (which is what is currently there), but with the term "WhatsApp Web", it will know what it is.

**Comment by viniciusgdr** [comment]
but there is no reason to send the user which device he is connected to, because he already knows. But if you really want to send it to the user you can change the answers with the conditionals

**Comment by kauanzito** [comment]
Ah yes. it is really not necessary for the user to see the type of device he uses, but it will be easier for him to understand (as I had already said), and also to not need to modify his own code (as you mentioned) every time Baileys makes a update...

**Comment by adiwajshing** [comment]
there isn't a convincing reason to update this function, I'd recommend a wrapper around this in your own code.

**Pull request closed without merging**
